name: anaglyph
description: A Flutter package which is made to help you create 3D anaglyph images
version: 0.0.1-alpha.1
# homepage: 
# repository: https://github.com/amir-msh/anaglyph
# issue_tracker: https://github.com/amir-msh/anaglyph/issues

environment:
  sdk: '>=2.18.6 <3.0.0' # '>=2.18.6 <3.0.0'
  flutter: ">=1.17.0" # ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

# screenshots:
#   - description: 'This screenshot shows the transformation of a number of bytes 
#   to a human-readable expression.'
#     path: path/to/image/in/package/500x500.webp
#   - description: 'This screenshot shows a stack trace returning a human-readable
#   representation.'
#     path: path/to/image/in/package.png

# funding:
#  - https://www.buymeacoffee.com/example_user
#  - https://www.patreon.com/some-account