name: anaglyph
description: A Flutter package made to help you create 3D apps as easy as possible!
version: 0.0.1-alpha.1
homepage: https://github.com/amir-msh/anaglyph
repository: https://github.com/amir-msh/anaglyph
issue_tracker: https://github.com/amir-msh/anaglyph/issues

environment:
  sdk: '>=2.18.6 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

funding:
  - https://www.buymeacoffee.com/amirmsh

screenshots:
  - description: '3D image No.1'
    path: screenshots/Screenshot_1674442485-min.png
  - description: '3D image No.2'
    path: screenshots/Screenshot_1674442480-min.png
  - description: '3D image No.3'
    path: screenshots/Screenshot_1674442418-min.png
  - description: '3D image No.4'
    path: screenshots/Screenshot_1674442402-min.png
  - description: '3D image on windows'
    path: screenshots/nebula-readme-example-min.png
  - description: '3D FlutterLogo on windows'
    path: screenshots/flutter-logo-readme-example-min.png

