name: anaglyph
description: A Flutter package made to help you create 3D anaglyph apps
version: 0.0.1-alpha.1
homepage: https://github.com/amir-msh/anaglyph
repository: https://github.com/amir-msh/anaglyph
issue_tracker: https://github.com/amir-msh/anaglyph/issues

environment:
  sdk: '>=2.18.6 <3.0.0' # '>=2.18.6 <3.0.0'
  flutter: ">=1.17.0" # ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

# TODO: add screenshots

# funding:
#  - https://www.buymeacoffee.com/amirmsh